#!/bin/python

# A script used for packaging AppImage.

import subprocess as sp
import argparse
import shutil
import logging
import random
import string
import pathlib
import os

logging.basicConfig(format="%(levelname)s:%(message)s")


class Packer:
    permissions = 0o755

    apprun_content = r"""#!/bin/sh
SELF=$(readlink -f "$0")
HERE=${SELF%/*}

export PATH="${HERE}/usr/bin:$PATH"
export LD_LIBRARY_PATH="${HERE}/usr/lib:$LD_LIBRARY_PATH"

EXEC=$(grep -e '^Exec=' "${HERE}"/*.desktop \
    | head -n 1 \
    | cut -d '=' -f 2 \
    | cut -d ' ' -f 1)
exec "${EXEC}" "$@"
"""

    desktop_content = """[Desktop Entry]
Name={name}
Exec={executable}
Icon=icon
Type=Application
Categories=Utility;"""

    # license for the icon can be found here https://github.com/mozilla/fxemoji
    icon = ""

    def __init__(
        self,
        executable_path: str,
        output_dir: str | None = None,
        packaging_tool: str = "appimagetool.AppImage",
        path: str = ".",
        arch: str = "x86_64",
        only_appdir: bool = False,
        keep_appdir: bool = False,
        extension: str | None = None,
    ) -> None:
        self.name: str = executable_path.split("/")[-1]
        self.executable_path: str = pathlib.Path(executable_path)
        self.packaging_tool: str = packaging_tool
        self.output_dir: pathlib.Path = (
            pathlib.Path(output_dir)
            if output_dir
            else pathlib.Path(f"/tmp/{self.name}.AppDir")
        )
        self.path = path
        self.arch = arch
        self.only_appdir = only_appdir
        self.keep_appdir = keep_appdir
        self.extension = extension

    # bootstrap all the necessary directories and package an AppImage
    def __call__(self) -> None:
        self.bootstrap_dirs()
        self.bootstrap_root()
        self.bootstrap_usr()
        if not self.only_appdir:
            self.package()
        if not (self.only_appdir or self.keep_appdir):
            self.cleanup()

    def _ldd_stdout(self) -> bytes:
        try:
            proc = sp.run(
                ["ldd", self.executable_path], stdout=sp.PIPE, check=True
            )
        except OSError:
            logging.error(f"Could not execute {self.packaging_tool}!")
        except sp.CalledProcessError as e:
            if e.returncode == 127:
                logging.error("ldd exited with errors!")
                raise SystemExit(1)
            if e.returncode == 1:
                return e.stdout
        else:
            return proc.stdout

    def _get_libraries(self) -> list[str]:
        lines: list[str] = self._ldd_stdout().decode().split()
        return list(filter(lambda i: "/lib" in i, lines))

    def _make_postfix(self) -> None:
        postfix = "".join(
            random.choices(string.digits + string.ascii_letters, k=8)
        )
        self.output_dir = pathlib.Path(f"{self.output_dir}.{postfix}")

    def _make_name(self) -> str:
        return f"{self.name}.{self.extension}" if self.extension else self.name

    def package(self) -> None:
        try:
            env = os.environ.copy()
            env.update({"ARCH": self.arch})
            sp.run(
                [
                    self.packaging_tool,
                    self.output_dir,
                    pathlib.Path(f"{self.path}/{self._make_name()}"),
                ],
                check=True,
                env=env,
            )
        except OSError:
            logging.error(f"Could not execute {self.packaging_tool}!")
        except sp.CalledProcessError:
            logging.error(f"{self.packaging_tool} exited with errors!")
            raise SystemExit(1)

    def cleanup(self) -> None:
        shutil.rmtree(self.output_dir)

    # make the basic structure
    def bootstrap_root(self) -> None:
        self.bootstrap_apprun()
        self.bootstrap_desktop()
        self.bootstrap_icon()

    def bootstrap_dirs(self) -> None:
        try:
            self.output_dir.mkdir()
        except FileExistsError:
            self._make_postfix()
            self.output_dir.mkdir()

        for subpath in ["usr", "usr/lib", "usr/bin"]:
            pathlib.Path(self.output_dir, subpath).mkdir()

    def bootstrap_icon(self) -> None:
        with open(f"{self.output_dir}/icon.svg", "x") as icon:
            icon.write(self.icon)

    def bootstrap_apprun(self) -> None:
        with open(f"{self.output_dir}/AppRun", "x") as desktop:
            desktop.write(self.apprun_content)
            os.chmod(f"{self.output_dir}/AppRun", self.permissions)

    def bootstrap_desktop(self) -> None:
        with open(f"{self.output_dir}/{self.name}.desktop", "x") as desktop:
            desktop.write(
                self.desktop_content.format(
                    name=self.name.capitalize(),
                    executable=self.name.lower(),
                )
            )

    def bootstrap_usr(self) -> None:
        for library in self._get_libraries():
            try:
                shutil.copy(library, f"{self.output_dir}/usr/lib/")
            except FileNotFoundError:
                logging.error(f"File {library} not found!")
                raise SystemExit(1)
        try:
            shutil.copy(self.executable_path, f"{self.output_dir}/usr/bin")
        except FileNotFoundError:
            logging.error(f"File {self.executable_path} not found!")
            raise SystemExit(1)


def main() -> None:
    parser = argparse.ArgumentParser(
        "AppImage Packer", description="A script for packaging AppImages."
    )
    parser.add_argument(
        "-e",
        "--executable-path",
        help="Path to the binary file you want to convert.",
        required=True,
    )
    parser.add_argument(
        "-p",
        "--packaging-tool",
        help="Path to the executable AppImageTool AppImage.",
        default="appimagetool.AppImage",
    )
    parser.add_argument(
        "-oa",
        "--output-appdir-path",
        help="The output AppDir directory.",
    )
    parser.add_argument(
        "-of",
        "--output-file-path",
        help="The output AppImage file directory.",
        default=".",
    )
    parser.add_argument(
        "--extension",
        help="extension of an output file.",
        default="",
    )
    parser.add_argument(
        "--arch",
        help="ARCH of an AppImage.",
        default="x86_64",
    )
    parser.add_argument(
        "--only-appdir",
        help="Make an AppDir only.",
        action="store_true",
        default=False,
    )
    parser.add_argument(
        "--keep-appdir",
        help="Keep an AppDir after packaging.",
        action="store_true",
        default=False,
    )
    args = parser.parse_args()
    packer = Packer(
        args.executable_path,
        args.output_appdir_path,
        args.packaging_tool,
        args.output_file_path,
        args.arch,
        args.only_appdir,
        args.keep_appdir,
        args.extension,
    )
    packer()


if __name__ == "__main__":
    main()
