#!/bin/python

# A script used for packaging AppImage.

from subprocess import run, CalledProcessError, PIPE
from typing import Iterable, ClassVar
from argparse import ArgumentParser
from dataclasses import dataclass
from contextlib import suppress
from shutil import copyfile, rmtree
from pathlib import Path
import logging
import os

logging.basicConfig(format="%(levelname)s:%(message)s")


@dataclass
class Layout:
    paths: Iterable[Path]
    root_dir: Path = Path("AppDir")
    symlinks: Iterable[Iterable[Path]] = ()

    def _make_dirs(self) -> None:
        for path in self.paths:
            path = self.root_dir / path
            path.mkdir(parents=True, exist_ok=True)

    def _make_symlinks(self) -> None:
        for path, target in self.symlinks:
            path = self.root_dir / path
            with suppress(FileExistsError):
                path.symlink_to(target, target_is_directory=True)

    def make_layout(self) -> None:
        self._make_dirs()
        self._make_symlinks()


@dataclass
class AppDirBootstraper:
    permissions: ClassVar[int] = 0o755
    apprun_content: ClassVar[str] = r"""#!/bin/sh
SELF=$(readlink -f "$0")
HERE=${SELF%/*}
export PATH="${HERE}/usr/bin:$PATH"
export LD_LIBRARY_PATH="${HERE}/usr/lib:$LD_LIBRARY_PATH"
EXEC=$(grep -e '^Exec=' "${HERE}"/*.desktop \
    | head -n 1 \
    | cut -d '=' -f 2 \
    | cut -d ' ' -f 1)
exec "${EXEC}" "$@"
"""
    desktop_content: ClassVar[str] = """[Desktop Entry]
Name={name}
Exec={executable}
Icon=icon
Type=Application
Categories=Utility;"""
    icon: ClassVar[str] = ""

    executable_name: str
    root_dir: Path = Path("AppDir")

    def _bootstrap_apprun(self) -> None:
        destination = self.root_dir / "AppRun"
        with open(destination, "x") as apprun:
            apprun.write(self.apprun_content)
        destination.chmod(self.permissions)

    def _bootstrap_desktop(self) -> None:
        destination = self.root_dir / f"{self.executable_name}.desktop"
        with open(destination, "x") as desktop:
            desktop.write(
                self.desktop_content.format(
                    name=self.executable_name, executable=self.executable_name
                )
            )

    def _bootstrap_icon(self) -> None:
        target = self.root_dir / "icon.svg"
        with open(target, "x") as icon:
            icon.write(self.icon)

    def bootstrap_appdir(self) -> None:
        self._bootstrap_apprun()
        self._bootstrap_desktop()
        self._bootstrap_icon()


@dataclass
class UsrBootstraper:
    binaries: Iterable[Iterable[Path]]
    libraries: Iterable[Iterable[Path]]
    root_dir: Path = Path("AppDir")

    def _copy_libraries(self) -> None:
        for library, path in self.libraries:
            target = (
                self.root_dir / path / library.parts[-1]
                if (self.root_dir / path).is_dir()
                else self.root_dir / path
            )
            copyfile(library, target)

    def _copy_binaries(self) -> None:
        for binary, path in self.binaries:
            target = (
                self.root_dir / path / binary.parts[-1]
                if (self.root_dir / path).is_dir()
                else self.root_dir / path
            )
            copyfile(binary, target)

    def bootstrap_usr(self) -> None:
        self._copy_libraries()
        self._copy_binaries()


@dataclass
class LibraryDefiner:
    executable_path: Path
    root_dir: Path = Path("usr/lib")

    def _ldd_stdout(self) -> bytes:
        try:
            proc = run(["ldd", self.executable_path], stdout=PIPE, check=True)
        except OSError:
            logging.error("Could not execute ldd!")
        except CalledProcessError as e:
            match e.returncode:
                case 127:
                    logging.error("ldd exited with error code 127!")
                    raise SystemExit(1)
                case 1:
                    return e.stdout
                case _:
                    logging.error("ldd exited with errors!")
                    raise SystemExit(1)
        else:
            return proc.stdout

    def _get_libraries(self) -> list[str]:
        lines = self._ldd_stdout().decode().split()
        return list(filter(lambda i: "/lib" in i, lines))

    def get_libraries(self) -> list[tuple[Path]]:
        libraries = [Path(path) for path in self._get_libraries()]
        return [(path, self.root_dir / path.parts[-1]) for path in libraries]


@dataclass
class Packer:
    executable_name: str
    output: Path | None = None
    arch: str = "x86_64"
    appimagetool: Path | str = "appimagetool.AppImage"
    root_dir: Path = Path("AppDir")

    def package(self) -> None:
        env = os.environ.copy()
        env["ARCH"] = self.arch
        try:
            run(
                [
                    self.appimagetool,
                    self.root_dir,
                    (
                        self.executable_name
                        if self.output is None
                        else self.output
                    ),
                ],
                check=True,
                env=env,
            )
        except OSError:
            logging.error(f"Could not execute {self.appimagetool}!")
        except CalledProcessError:
            logging.error(f"{self.appimagetool} exited with errors!")
            raise SystemExit(1)

    def _get_libraries(self) -> list[str]:
        lines = self._ldd_stdout().decode().split()
        return list(filter(lambda i: "/lib" in i, lines))


def main() -> None:
    parser = ArgumentParser(
        "appimage-packer", description="A script for packaging AppImages."
    )
    parser.add_argument(
        "-e",
        "--executable-path",
        help="Path to the binary file you want to convert.",
        required=True,
    )
    parser.add_argument(
        "-p",
        "--appimagetool",
        help="Path to the executable AppImageTool AppImage.",
        default="appimagetool.AppImage",
    )
    parser.add_argument(
        "-o",
        "--output",
        help="The output AppImage file or directory.",
        default="",
    )
    parser.add_argument(
        "--appdir-location",
        help="Location of an AppDir.",
        default="/tmp/",
    )
    parser.add_argument(
        "--arch",
        help="ARCH of an AppImage.",
        default="x86_64",
    )
    parser.add_argument(
        "--keep-appdir",
        help="Keep an AppDir after packing.",
        action="store_true",
    )
    parser.add_argument(
        "--appdir-only",
        help="Make only an AppDir.",
        action="store_true",
    )
    args = parser.parse_args()

    executable_path = Path(args.executable_path)
    executable = executable_path.parts[-1]
    root_dir = Path(args.appdir_location) / f"{executable}.AppDir"
    output = args.output if args.output else executable

    if root_dir.exists():
        rmtree(root_dir)

    layout = Layout(["usr/lib", "usr/bin"], root_dir)
    library_definer = LibraryDefiner(executable_path)
    usr_bootstraper = UsrBootstraper(
        [
            [
                executable_path,
                Path("usr/bin"),
            ]
        ],
        library_definer.get_libraries(),
        root_dir,
    )
    appdir_bootstraper = AppDirBootstraper(executable, root_dir)
    packer = Packer(
        executable,
        output,
        args.arch,
        args.appimagetool,
        root_dir,
    )

    layout.make_layout()
    usr_bootstraper.bootstrap_usr()
    appdir_bootstraper.bootstrap_appdir()

    if not args.appdir_only:
        packer.package()

    if not args.keep_appdir and not args.appdir_only:
        rmtree(root_dir)


if __name__ == "__main__":
    main()
