#!/bin/python

# A script used for packaging AppImage.

import subprocess as sp
import argparse
import shutil
import logging
import os

logging.basicConfig(format="%(levelname)s:%(message)s")


class Packer:
    permissions = 0o755

    apprun_content = r"""#!/bin/sh
SELF=$(readlink -f "$0")
HERE=${SELF%/*}

export PATH="${HERE}/usr/bin:$PATH"
export LD_LIBRARY_PATH="${HERE}/usr/lib:$LD_LIBRARY_PATH"

EXEC=$(grep -e '^Exec=' "${HERE}"/*.desktop | head -n 1 | cut -d '=' -f 2 | cut -d ' ' -f 1)
exec "${EXEC}" "$@"
"""

    desktop_content = """[Desktop Entry]
Name={name}
Exec={executable}
Icon=icon
Type=Application
Categories=Utility;"""

    # license for the icon can be found here https://github.com/mozilla/fxemoji
    icon = r"""<?xml version="1.0" encoding="iso-8859-1"?>
<!-- Generator: Adobe Illustrator 18.1.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 512 512" enable-background="new 0 0 512 512" xml:space="preserve">
<g id="Layer_3">
	<path fill="#FFAA3B" d="M501.617,489.617c0,6.6-5.4,12-12,12H22.383c-6.6,0-12-5.4-12-12V22.383c0-6.6,5.4-12,12-12h467.234
		c6.6,0,12,5.4,12,12V489.617z"/>
</g>
<g id="Layer_4">
	<path fill="#FFE564" d="M412.026,251.12c-2.933-4.294-2.933-9.946,0-14.24l20.587-30.141c4.36-6.383,2.011-15.15-4.956-18.497
		l-32.9-15.809c-4.687-2.252-7.513-7.147-7.12-12.332l2.759-36.396c0.584-7.708-5.833-14.125-13.541-13.541l-36.396,2.759
		c-5.185,0.393-10.08-2.433-12.332-7.12l-15.809-32.9c-3.348-6.967-12.115-9.316-18.497-4.956L263.68,88.534
		c-4.294,2.933-9.946,2.933-14.24,0L219.3,67.947c-6.383-4.36-15.15-2.011-18.497,4.956l-15.809,32.9
		c-2.252,4.686-7.147,7.513-12.332,7.12l-36.396-2.759c-7.708-0.584-14.125,5.833-13.541,13.541l2.759,36.396
		c0.393,5.185-2.433,10.08-7.12,12.332l-32.9,15.809c-6.967,3.348-9.316,12.115-4.956,18.497l20.587,30.141
		c2.933,4.294,2.933,9.946,0,14.24L80.507,281.26c-4.36,6.383-2.011,15.15,4.956,18.497l32.9,15.809
		c4.687,2.252,7.513,7.147,7.12,12.332l-2.759,36.396c-0.584,7.708,5.833,14.125,13.541,13.541l36.396-2.759
		c5.185-0.393,10.08,2.433,12.332,7.12l15.809,32.9c3.348,6.967,12.115,9.316,18.497,4.956l30.141-20.587
		c4.294-2.933,9.946-2.933,14.24,0l30.141,20.587c6.383,4.36,15.15,2.011,18.497-4.956l15.809-32.9
		c2.252-4.687,7.147-7.513,12.332-7.12l36.396,2.759c7.708,0.584,14.125-5.833,13.541-13.541l-2.759-36.396
		c-0.393-5.185,2.433-10.08,7.12-12.332l32.9-15.809c6.967-3.348,9.316-12.115,4.956-18.497L412.026,251.12z"/>
</g>
<g id="Layer_5">
	<path fill="#1D771F" d="M385.507,240.62c-119.231,0-215.887,83.871-215.887,152.238c0,41.561,19.708,79.567,52.296,108.759h267.702
		c6.6,0,12-5.4,12-12V262.522C468.09,248.357,428.25,240.62,385.507,240.62z"/>
</g>
<g id="Layer_6">
	<path fill="#2BA52E" d="M496.864,499.149C461.831,466.661,413.869,423.769,364,384c-79-63-178.087-105-287-105
		c-22.176,0-45.008,7.069-66.617,18.574v192.043c0,6.6,5.4,12,12,12h467.234C492.337,501.617,494.845,500.69,496.864,499.149z"/>
</g>
</svg>"""

    def __init__(
        self,
        executable_path: str,
        output_dir: str | None = None,
        packaging_tool: str = "appimagetool.AppImage",
    ) -> None:
        self.name: str = executable_path.split("/")[-1]
        self.executable_path: str = executable_path
        self.libraries: list[str] = self.get_libraries()
        self.packaging_tool = packaging_tool

        if output_dir:
            self.output_dir: str = output_dir
        else:
            self.output_dir: str = f"/tmp/{self.name}.AppDir"

    # bootstrap all the necessary directories and package an AppImage
    def __call__(self, appdir_only: bool = False) -> None:
        self.bootstrap_dirs()
        self.bootstrap_root()
        self.bootstrap_usr()
        if not appdir_only:
            self.package()

    def ldd_stdout(self) -> bytes:
        try:
            proc = sp.run(
                ["ldd", self.executable_path], stdout=sp.PIPE, check=True
            )
        except OSError:
            logging.error(f"Could not execute {self.packaging_tool}!")
        except sp.CalledProcessError:
            logging.error("ldd exited with errors!")
            raise SystemExit(1)
        else:
            return proc.stdout

    def get_libraries(self) -> list[str]:
        lines: list[str] = self.ldd_stdout().decode().split()
        return list(filter(lambda i: "/lib" in i, lines))

    def package(self) -> None:
        try:
            sp.run(
                [
                    self.packaging_tool,
                    self.output_dir,
                    f"{self.name}.AppImage",
                ],
                check=True,
            )
        except OSError:
            logging.error(f"Could not execute {self.packaging_tool}!")
        except sp.CalledProcessError:
            logging.error(f"{self.packaging_tool} exited with errors!")
            raise SystemExit(1)

    # make the basic structure
    def bootstrap_root(self) -> None:
        self.bootstrap_apprun()
        self.bootstrap_desktop()
        self.bootstrap_icon()

    def bootstrap_dirs(self) -> None:
        try:
            os.mkdir(self.output_dir)
        except FileExistsError:
            if self.output_dir in [".", "/", "./"]:
                logging.warn(
                    "Think twice before doing it. Check the source code."
                )
                raise SystemExit(1)
            shutil.rmtree(self.output_dir)
            os.mkdir(self.output_dir)

        for subpath in ["usr", "usr/lib", "usr/bin"]:
            os.mkdir(f"{self.output_dir}/{subpath}")

    def bootstrap_icon(self) -> None:
        with open(f"{self.output_dir}/icon.svg", "x") as icon:
            icon.write(self.icon)

    def bootstrap_apprun(self) -> None:
        with open(f"{self.output_dir}/AppRun", "x") as desktop:
            desktop.write(self.apprun_content)
            os.chmod(f"{self.output_dir}/AppRun", self.permissions)

    def bootstrap_desktop(self) -> None:
        with open(f"{self.output_dir}/{self.name}.desktop", "x") as desktop:
            desktop.write(
                self.desktop_content.format(
                    name=self.name.capitalize(),
                    executable=self.name.lower(),
                )
            )

    def bootstrap_usr(self) -> None:
        for library in self.libraries:
            try:
                shutil.copy(library, f"{self.output_dir}/usr/lib/")
            except FileNotFoundError:
                logging.error(f"File {library} not found!")
                raise SystemExit(1)
        try:
            shutil.copy(self.executable_path, f"{self.output_dir}/usr/bin")
        except FileNotFoundError:
            logging(f"File {self.executable_path} not found!")
            raise SystemExit(1)


def main() -> None:
    parser = argparse.ArgumentParser(
        "AppImage Packer", description="A script for packaging AppImages."
    )
    parser.add_argument(
        "-e",
        "--executable-path",
        help="Path to the binary file you want to convert.",
        required=True,
    )
    parser.add_argument(
        "-p",
        "--packaging-tool",
        help="Path to the executable AppImageTool AppImage.",
        default="appimagetool.AppImage",
    )
    parser.add_argument(
        "-d", "--directory", help="The output AppDir directory."
    )
    parser.add_argument(
        "--appdir-only",
        help="Make only an AppDir.",
        action="store_true",
        default=False,
    )
    args = parser.parse_args()
    packer = Packer(args.executable_path, args.directory, args.packaging_tool)
    packer(args.appdir_only)


if __name__ == "__main__":
    main()
