#!/bin/python
import argparse
import subprocess


class SoundControl:
    @staticmethod
    def increase(percent: int = 5) -> None:
        subprocess.run(["pulsemixer", "--change-volume", f"+{percent}"])
        output = subprocess.run(
            ["pulsemixer", "--get-volume"], stdout=subprocess.PIPE
        )
        volume = output.stdout.split()[0]
        subprocess.run(
            [
                "notify-send",
                "-t",
                "3000",
                "Sound",
                f"Current volume is {volume.decode()}%",
            ]
        )

    @staticmethod
    def decrease(percent: int = 5) -> None:
        subprocess.run(["pulsemixer", "--change-volume", f"-{percent}"])
        output = subprocess.run(
            ["pulsemixer", "--get-volume"], stdout=subprocess.PIPE
        )
        volume = output.stdout.split()[0]
        subprocess.run(
            [
                "notify-send",
                "-t",
                "3000",
                "Sound",
                f"Current volume is {volume.decode()}%",
            ]
        )

    @staticmethod
    def mute() -> None:
        subprocess.run(["pulsemixer", "--toggle-mute"])
        output = subprocess.run(
            ["pulsemixer", "--get-mute"], stdout=subprocess.PIPE
        )
        muted = output.stdout.decode()[0]
        if muted == "1":
            mute_state = "Muted"
        if muted == "0":
            mute_state = "Unmuted"
        subprocess.run(["notify-send", "-t", "3000", "Sound", mute_state])


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="sound-control",
        description="Program to control sound and show the volume.",
    )
    parser.add_argument(
        "action", help='Can be: "increase", "decrease", "mute".'
    )
    parser.add_argument("-v", "--value", help="Number")
    args = parser.parse_args()
    match args.action:
        case "increase":
            if args.value:
                SoundControl.increase(args.value)
            else:
                SoundControl.increase()
        case "decrease":
            if args.value:
                SoundControl.decrease(args.value)
            else:
                SoundControl.decrease()
        case "mute":
            SoundControl.mute()


if __name__ == "__main__":
    main()
